# Generated by Django 5.0.1 on 2024-01-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_order_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('delivered', 'delivered')], default='pending', max_length=255),
        ),
    ]
